### ISSUE TITLE
Windows & Anaconda install improvements

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#10]
**Overview**
Many windows users are using Anaconda, which has had occasional issues with installing.

Issues seen are:
- `pip3 install datapane` not installing pyarrow from the recommended wheel, instead trying to compile it from source (which usually fails due to missing libraries)
- Datapane not appearing in path post-install (i.e. you can run with `python -m datapane.client` but it's not in path)

Although we have windows environments in CI, these are based on the default windows Python package (i.e. what you get when you install Python from the Windows store), and not Anaconda.

We should investigate how to support all common combinations of Windows (10+) and Anaconda.

**Notes**
- Some users are on 32bit Anaconda Python - should we recommend 64bit only?
- The PATH issue may occur on default Windows install, but requires more testing
- Some Anaconda users are installing without issue, so we need to figure out why some are not pulling down the pyarrow wheel correctly

**Comment by mands** [comment]
We prob need a specific conda package - Jupyter has one for `conda` and one for `pip`

![image](https://user-images.githubusercontent.com/1010043/86054187-9d284200-ba51-11ea-9c52-a592c8400d49.png)

I think conda supports installing "pure-Python" packages from pip, but generally only recommended for software not already packaged by conda

**Comment by mands** [comment]
see #11 - we should be ready to install from conda-forge shortly

**Comment by mands** [comment]
Digging into Path issue on Windows - seems like standard Python install (e.g. that from Windows Store), doesn't add the `Scripts` directory to the user's %PATH% - as indicated below

![image](https://user-images.githubusercontent.com/1010043/86819434-8e5c1380-c07f-11ea-8769-15fe4f5bed6c.png)

**Comment by mands** [comment]
closing as docs updated with all known Windows issues and potential fixes - see https://docs.datapane.com/tutorials/tut-getting-started
