### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by yelotmani** [datapane/datapane#106]
Hi, 

After the upgrade we can no longer save local HTML of report using DataTable, and that's an important feature of the report i built over the past few months. Wondering if this will be brought back sometime soon, or if we can have a DataTable without the new advanced features such as we can still save locally.

Thanks,
Youssef

_Originally posted by @joelowj in https://github.com/datapane/datapane/discussions/101_

**Comment by mands** [comment]
Hi there - sorry for the wait on this, there were some technical issues, however happy to announce that DataTable is now supported again when saving locally from Datapane version 0.11.6 onwards.
