### ISSUE TITLE
Add datapane to conda-forge?

### ISSUE THREAD

**Issue by giswqs** [datapane/datapane#11]
Thank you for developing this great package! I plan to add it as a dependency for my [geemap](https://github.com/giswqs/geemap) Python package. Do you plan to make datapane available on [conda-forge](https://github.com/giswqs/geemap)? Thanks.

**Comment by mands** [comment]
Hi there, thanks for your comment - yes absolutely, we're planning to try and get it into conda-forge asap, hopefully this week!

**Comment by mands** [comment]
Package accepted by conda-forge, waiting for it to become available - can track in https://github.com/conda-forge/datapane-feedstock

**Comment by giswqs** [comment]
Awesome! Looking forward to it.

**Comment by mands** [comment]
Now live on conda-forge! 

https://anaconda.org/conda-forge/datapane - can install as `conda install -c conda-forge datapane`
