### ISSUE TITLE
MPL Cropping

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#111]
There are some issues with when creating reports with seaborn or MPL plots, where they appear cropped on either axes. Generally making sure that the matplotlib gcf has `.tightlayout()` applied has fixed the issue, but this doesn't always lead to expected results.

It seems this is a common problem when using matplotlib's `save_fig` function, which we use under the hood:
- https://stackoverflow.com/questions/45239261/matplotlib-savefig-text-chopped-off
- https://stackoverflow.com/questions/6774086/why-is-my-xlabel-cut-off-in-my-matplotlib-plot

This isn't strictly a datapane bug, but we can probably improve the user experience here by adding some padding or making the layout tighter by default.

**Comment by shahinrostami** [comment]
Moved this issue to a feature request after confirming with @lanthias.

New location: https://datapane.nolt.io/25
