### ISSUE TITLE
dp.Report failed when using docker image

### ISSUE THREAD

**Issue by giswqs** [datapane/datapane#12]
Following the datapane [configuration guidelines](https://docs.datapane.com/tutorials/configuration-and-dependencies), I created a [giswqs/geemap-datapane](https://hub.docker.com/repository/docker/giswqs/geemap-datapane) docker image based on [nstack/datapane-python-runner](https://hub.docker.com/r/nstack/datapane-python-runner). The Python script failed at the last line `dp.Report(dp.Plot(Map)).publish(name='geemap_folium_map')` with a `TypeError: can't pickle weakref objects`. Any advice? Thanks.

https://datapane.com/giswqs/scripts/geemap_test/

![](https://i.imgur.com/bndYwBh.png)

![](https://i.imgur.com/sgA5p42.png)

**Dockerfile**
```
from nstack/datapane-python-runner:latest
RUN pip3 install --user -U geemap
```

**datapane.yaml**
```
name: geemap_test
script: geemap_test.py # this could also be ipynb if it was a notebook
container_image_name: giswqs/geemap-datapane
```
**geemap.test.py**
```
import folium
import datapane as dp 
import geemap.eefolium as geemap
import ee
import os

secret = dp.Variable.get(name='EARTHENGINE_TOKEN')
ee_token = secret.value

credential = '{"refresh_token":"%s"}' % ee_token
credential_file_path = os.path.expanduser("~/.config/earthengine/")
os.makedirs(credential_file_path, exist_ok=True)
with open(credential_file_path + 'credentials', 'w') as file:
    file.write(credential)

# m = folium.Map(location=[45.5236, -122.6750])
ee.Initialize()
Map = geemap.Map(center=[40,-100], zoom=4)

# Add Earth Engine dataset
image = ee.Image('USGS/SRTMGL1_003')

# Set visualization parameters.
vis_params = {
  'min': 0,
  'max': 4000,
  'palette': ['006633', 'E5FFCC', '662A00', 'D8D8D8', 'F5F5F5']}

# Print the elevation of Mount Everest.
xy = ee.Geometry.Point([86.9250, 27.9881])
elev = image.sample(xy, 30).first().get('elevation').getInfo()
print('Mount Everest elevation (m):', elev)

# Add Earth Engine layers to Map
Map.addLayer(image, vis_params, 'DEM')
Map.addLayer(xy, {'color': 'red'}, 'Mount Everest')

# Center the map based on an Earth Engine object or coordinates (longitude, latitude)
# Map.centerObject(xy, 4)
Map.setCenter(86.9250, 27.9881, 4)

# Map.addLayerControl() # This line is not needed for ipyleaflet-based Map.
Map.setControlVisibility()

dp.Report(dp.Plot(Map)).publish(name='geemap_folium_map')
```

**Comment by lanthias** [comment]
Thanks for this! Are you able to publish the report successfully when you
run the geemap.test.py Python code on your own environment (as opposed to
on Datapane)?





-- 
Leo Anthias
CEO & Co-Founder at Datapane
datapane.com
M: +447595586697 <+44%207595%20586697>

**Comment by giswqs** [comment]
If I change the datapane.yaml to the following (i.e., removing my own docker image and adding geemap to the requirements section), the report can publish successfully. 

https://datapane.com/giswqs/reports/geemap_folium_map_d7ff9127/

```
name: geemap_test
script: geemap_test.py # this could also be ipynb if it was a notebook
requirements:
 - geemap
```

**Comment by lanthias** [comment]
Thanks, that's helpful to know. We're currently looking into this.

Just to confirm @giswqs, if you run the above Python code in your local Python environment (i.e. you do not deploy it as a script to Datapane, but instead run it in e.g. Jupyter), does it succeed in publishing the report?

**Comment by giswqs** [comment]
Yes, I am able to run it locally and preview the report. Check the [notebook](https://gist.github.com/giswqs/62774e84ec50cfb63875134ce45dd111) example I used. The run output on datapane.com shows that `Mount Everest elevation (m): 8729`, indicating that all lines were successfully executed except the last line `de.Report().publish()`. I am pretty sure it is caused by the customized docker image ([giswqs/geemap-datapane](https://hub.docker.com/repository/docker/giswqs/geemap-datapane)). If I don't use the customized docker image and just add `geemap` to the requirements section of  `datapane.yaml`, the report can be published just fine. So here is the question: is the docker image [nstack/datapane-python-runner](https://hub.docker.com/r/nstack/datapane-python-runner) the same one being used on datapane.com? The one on dockerhub was updated one month ago. Did it include functionality to render folium map?   


![](https://i.imgur.com/vIgRtwD.gif)

**Comment by mands** [comment]
Hi @giswqs - thanks for the opening the issue and the detailed report - that's really helpful. I've just updated the image on dockerhub (`nstack/nstack/datapane-python-runner`) to track the latest in `pip`. Sorry about that - we're currently in the process of getting the `datapane` organisation on DockerHub that will make this all a lot easier :)

Fantastic maps btw! :+1:

**Comment by giswqs** [comment]
@mands Thanks for the info. Is my docker image ([giswqs/geemap-datapane](https://hub.docker.com/repository/docker/giswqs/geemap-datapane)) being cached on the datapane.com server? I just deployed the same script, and I still got the same error message. Any advice? 

This `datapane.yaml` works:
```
name: geemap_test
script: geemap_test.py 
container_image_name: nstack/datapane-python-runner
requirements:
 - geemap
```

This `datapane.yaml` does not work:
```
name: geemap_test
script: geemap_test.py 
container_image_name: giswqs/geemap-datapane
```
Dockerfile for [giswqs/geemap-datapane](https://hub.docker.com/repository/docker/giswqs/geemap-datapane) 
```
from nstack/datapane-python-runner
RUN pip3 install --user -U geemap
```

**Comment by mands** [comment]
Hi @giswqs - yes we do cache images on Datapane, however only those that have a specific version tag, i.e. `nstack/datapane-python-runner:0.6.6`, however if the tag ends in `:latest` then we always try to repull the image and invalidate the cache (this is default Docker behaviour).

I think the issue may be your machine is caching the `datapane-python-runner` locally when building. Pulling down giswqs/geemap-datapane shows datapane version 0.6.0, rather than 0.6.6.

```bash
$ docker pull docker.io/giswqs/geemap-datapane:latest                                                                                                                                                          
$ docker run -it docker.io/giswqs/geemap-datapane:latest                                                                                                                                                          
[usercode@074c5dccae7d ~]$ datapane --version
datapane, version 0.6.0 (v0.6.0-1-ge2df122a)
```

Quick fix is to add the version number to the Dockerfile for `giswqs/geemap-datapane` e.g.

```dockerfile
from nstack/datapane-python-runner:0.6.6
RUN pip3 install --user -U geemap
```

Hope that helps - do let me know if you run into any further issues

**Comment by giswqs** [comment]
@mands Thank you for your advice! I am docker beginer. Rebuilding the docker image solved the issue. The report was published successfully. Interestingly, when I checked the Run Report on datapane.com, I can see the the following error. So it seems the script was executed successfully and the report was published even with the import error. I am not sure where this error comes from. I have not encountered this on my local computer. 

https://datapane.com/giswqs/reports/geemap_folium_map_496c611a/

![](https://i.imgur.com/ssls4OO.png)

**Comment by giswqs** [comment]
I used the following two lines to suppress the warnings. 

```
import logging
logging.getLogger( 'googleapiclient.discovery_cache').setLevel(logging.ERROR)
```

**Comment by mands** [comment]
Just saw this - yes that hopefully wouldn't crash the report generation - we capture and send out those logs just for user feedback and information.

Not entirely sure why it doesn't occur locally but does when running in docker - perhaps adding the missing `oauth2client` library to your docker requirements.txt file will help
