### ISSUE TITLE
Overwrite existing report

### ISSUE THREAD

**Issue by giswqs** [datapane/datapane#13]
I would like to use datapane to publish Interactive Google Earth Engine (GEE) maps. However, GEE data layers are only valid for two to three days. After the token expire, users will need to regenerate GEE data layers. 

If I use the following code publish the report the second time, datapane will generate a new URL with 8 random characters at the end (e.g., `geemap_folium_map_ea074e4f`). Is it possible to overwrite the existing report and keep the same URL (`geemap_folium_map`)? The reason for this is that if I already embed the link (`geemap_folium_map`) in a social media post, I could not keep going back to update the URL. 
```
dp.Report(dp.Plot(Map)).publish(name='ee_folium_map')
```

The original report (GEE data layers already expired. It won't show up on the map)
https://datapane.com/giswqs/reports/geemap_folium_map/

The republished report with GEE layers, but the link has changed. 
https://datapane.com/giswqs/reports/geemap_folium_map_ea074e4f/

**Comment by giswqs** [comment]
I figured out the workaround by deleting the existing report and republishing the report. In this way, the url remains the same.

**Comment by mands** [comment]
Hi @giswqs - yes deleting and recreating will work in the meantime.

We're actually working on adding versioning to reports so you can push new versions to the same URL and go back and view the previous versions - this should be live hopefully by the end of the week.

**Comment by giswqs** [comment]
This would be a welcome feature. Thank you.
