### ISSUE TITLE
DataTable Error No Objects to Concat

### ISSUE THREAD

**Issue by gelolopez11** [datapane/datapane#130]
### System Information

- OS: MacOS Big Sur
- Python version:
- Python environment: pip / conda conda
- Using jupyter: true / false true
- Datapane version: 0.11.2

### Bug / Issue

Hi, 

I created a dataframe in my script and named it as summaryfile. Now when I run a script to create a data table,

`dp.Report(dp.DataTable(summaryfile)).upload(name = "sample")`

this returns an error, "No Objects to Concatenate". 

Would love to get help for this! thanks.

**Comment by mands** [comment]
Thanks for raising - this is fixed in version `0.11.10`
