### ISSUE TITLE
unable to install python on windows 10

### ISSUE THREAD

**Issue by mayz6121** [datapane/datapane#132]
when I install python 3.9.6 or other versions, this error has been occurred and I cant Use it...
![image](https://user-images.githubusercontent.com/87663211/126193051-0d877c22-c0b7-4580-aee3-21026b99f1b8.png)

**Comment by mands** [comment]
Sorry - this looks like a windows Python issue - you can install Python directly from the Windows store now so I'd recommend trying that - see https://docs.python.org/3/using/windows.html for more information
