### ISSUE TITLE
Can not update Plotly because of Datapane restriction

### ISSUE THREAD

**Issue by dummybambang** [datapane/datapane#141]
### System Information

- OS: Windows 10
- Python version: 3.8.10
- Python environment: conda
- Using jupyter:  false
- Datapane version: 0.11.11

### Bug / Issue

This issue is relevant to https://github.com/conda-forge/plotly-feedstock/issues/96

The problem is we can't update to Plotly 5.1.0 because the Datapane told us to have Plotly version under 5.

If anyone have any solution for this issue, please share your thoughts here :)

**Comment by sleepybunn** [comment]
hello,

i experience this issue too, on 2 different laptops, plotly is stuck in v4.14.3, if datapane is installed, even has been updated to v0.11.11

if we tried to update the plotly via conda, package conflict error appears, as explained on github link above

**Comment by mands** [comment]
Hi,

Thanks for raising - we're looking into now and should have a release out very shortly that will support both v4 and v5 versions of Plotly.
