### ISSUE TITLE
save method is broken

### ISSUE THREAD

**Issue by joaovitordeon** [datapane/datapane#143]
### System Information

- OS: Ubuntu 20.04.2 LTS
- Python version: 3.7.6
- Python environment: pip / conda
- Using jupyter: true
- Datapane version: 0.11.11

### Bug / Issue

The 'save' method of Report is saving a blank HTML file.

This become to happen when i updated the datapane to newest version (0.11.11) ...

The result of HTML after update:

![Screenshot from 2021-08-10 10-57-59](https://user-images.githubusercontent.com/26352625/129965020-edf261d5-d7ff-4c59-afb9-ab021cd52ce8.png)

**Comment by mands** [comment]
Hi,

Sorry we've been unable to reproduce this - can you try again using the 0.12.x series and provide your sample code if the problem persists.

**Comment by joaovitordeon** [comment]
Seems in datapane version 0.12.1 just fixed it

**Comment by mands** [comment]
Great to hear - thanks!
