### ISSUE TITLE
Table headers right-justified instead of centered

### ISSUE THREAD

**Issue by inigohidalgo** [datapane/datapane#149]
### System Information

- OS: Windows 10
- Python version: 3.8.10
- Python environment: conda
- Using jupyter: true
- Datapane version: 0.12.0

### Bug / Issue

Hello @mands, thanks for the encoding fix in 0.12.0. That was fully solved but now I have a new issue with the locally saved reports. In `Table` blocks the table headings are right-justified where in 0.11.11 they were centered. Further, the formatting of the tables is (in my opinion) less clean-looking, with 2 different border colors, black vertical and grey horizontal, compared to just horizontal grey lines in 0.11.11.

Old:
![image](https://user-images.githubusercontent.com/20395965/128697082-a1808d55-a01a-4a0a-9653-381284db7f7b.png)

New:
![image](https://user-images.githubusercontent.com/20395965/131327936-8c141394-6c30-44e6-9b23-8c9b90813c58.png)

**Comment by inigohidalgo** [comment]
Further info: when I use a styled dataframe (`df.style...`) instead of a pure dataframe, the dataframe displays correctly (centered headers, only grey horizontal lines and correct encoding). This is good enough for my purposes since I will be using formatting for all my tables, but will leave the issue open so you are aware of this.

**Comment by mands** [comment]
Hi @inigohidalgo - thanks for raising, this has been resolved and will be released as 0.12.1 in the next few days
