### ISSUE TITLE
Build Script Exception with Jupyter Notebook

### ISSUE THREAD

**Issue by WayneLambert** [datapane/datapane#15]
I have attempted to deploy a Jupyter notebook to the DataPane web service using the following `datapane.yaml` config as below:

```yml
name: imdb_movies
script: imdb_movies.ipynb
repo: https://github.com/WayneLambert/library-python/blob/master/data_science/notebooks
parameters:
  - name: query
    description: Analysis of iMDB Movie Dataset
    required: False
    type: string
```

Running the script, I received the following traceback:

```
Unhandled Exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/datapane/runner/exec_script.py", line 40, in run
    res_scope = exec_mod(script.script)
  File "/usr/local/lib/python3.7/site-packages/datapane/runner/exec_script.py", line 164, in exec_mod
    res_scope = runpy.run_path(str(script_path), init_globals=globalscope, run_name=RUN_NAME)
  File "/usr/lib64/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "imdb_movies.py", line 44, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
NameError: name 'get_ipython' is not defined
```

It appears to suggest that an `imdb_movies.py` file is required. The file I input for the script was called `imdb_movies.ipynb`.

Following a discussion with Leo, it appears as though the offending cell in my notebook is:

```python
%matplotlib inline
```

Is there any way that the deployment script could work around this? If it isn't fundamental to the functionality of the HMTL report, it would be ideal ignoring it and allowing the notebook to still build.

**Comment by mands** [comment]
Hi @WayneLambert 

Ah yep this should be an easy fix in the notebook conversion during deployment - will make a patch to land next week.

Cheers!
