### ISSUE TITLE
Dataexplorer not supported on this dataset

### ISSUE THREAD

**Issue by njss** [datapane/datapane#158]
- OS: windows 10
- Python version: 3.9
- Python environment: pip 
- Using jupyter: false (VSCode)
- Datapane version: Latest

### Bug / Issue
I create a new report table (from a standard csv dataset).
Dataexplorer is not activated and shows the message: Dataexplorer not supported on this dataset

**Comment by mands** [comment]
Hi @njss ,

Could you provide a bit more information so we can track this bug down - we've 

- your version of pandas and numpy
- the CSV / dataset (if you can't provide the exact CSV then a sample CSV that demonstrates the issue would be fine)
- do you see the same issue if you use this dataset?

```python
import vega_datasets as vd
df = vd.data.cars()
...
```

Thanks!

**Comment by shahinrostami** [comment]
> * OS: windows 10
> * Python version: 3.9
> * Python environment: pip
> * Using jupyter: false (VSCode)
> * Datapane version: Latest
> 
> ### Bug / Issue
> I create a new report table (from a standard csv dataset). Dataexplorer is not activated and shows the message: Dataexplorer not supported on this dataset

Hello @njss!

I hope you've resolved the issue in the meantime, but please let us know if we need to re-open it!
