### ISSUE TITLE
Deploying from CLI

### ISSUE THREAD

**Issue by WayneLambert** [datapane/datapane#16]
When you run the command `datapane script deploy --help` for guidance, it returns the following output:

```sh
Usage: datapane script deploy [OPTIONS]

  Package and deploy a Python script or Jupyter notebook as a Datapane
  Script bundle

Options:
  --config PATH
  --script PATH
  --name TEXT
  --visibility [PUBLIC|ORG|PRIVATE]
  --help                          Show this message and exit.
```

It suggests that the --config flag accepts a path argument, however, for my project when I'm in the project's `src` directory on the command line and run either the command:

```sh
$  datapane script deploy --config data_science/notebooks/datapane.yaml
# OR
$  datapane script deploy --config ./data_science/notebooks/datapane.yaml
```

it returns:

```sh
Please run from source directory
```

If I navigate to the folder containing the yaml file and run the script from there, then I can successfully run the deploy script.

Is it possible to run a deploy script from your project's `src` directory by passing the the relative path to the command as a flag argument?

**Comment by mands** [comment]
closing for now due to refactoring script deployment
