### ISSUE TITLE
jsonschema>=4.2.1 incompatible with altair 4.1 transform_fold()

### ISSUE THREAD

**Issue by fgenoese** [datapane/datapane#178]
See: https://github.com/altair-viz/altair/issues/2525

The best fix would be not to require jsonschema>=4.2.1 in datapane, because it leads to performance problems in other areas of altair (see: https://github.com/altair-viz/altair/issues/2501)

Could we release this constraint in datapane?

**Comment by mands** [comment]
fixed and released as 0.13.1 - thanks for raising the issue! 👍

**Comment by fgenoese** [comment]
Thanks for the quick fix!
