### ISSUE TITLE
Report layout customisation

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#18]
## Overview
As someone building a report, I want to be able to customise the layout in a grid, instead of just having a sequential list of blocks, so that I can have more flexible reports.

This has come up with a good chunk of current users, and is something that should be made a lot easier by the recent migration to an XML-backed report structure.

## Implementation Ideas
There are a few ways we could structure the end-user API. I've chatted to a few users, and the simplest to start with seems to be having some column and row primitives, but I'm open to suggestions.

We could wrap the [Tailwind flex/grid html classes](https://tailwindcss.com/components/flexbox-grids/) into some Python classes, like this:

```python
dp.Report(
  dp.Row(
    dp.Column(dp.Table(df), width='1/3'),
    dp.Column(dp.Table(df), width='2/3')
  )
)
```

## Other options considered

The other options I considered were: allowing the user to actually write HTML/CSS, but many people writing Python reports may not know these, and it becomes very complex. Alternatively, I considered having the properties on the blocks themselves...

```python
dp.Report(
    dp.Table(df, width='200px'),
    dp.Table(df, width='2/3') # can't see how this would work
)
```

But I feel this is the wrong level of control, as we'd rather push to a proper grid system. 

## Notes
- Some of the blocks we support are not responsive (i.e. Altair) - so we would need to document this. How do we deal with overflow?

**Comment by mands** [comment]
closed by commit https://github.com/datapane/datapane/commit/31a40f87346205ecce403864153d6a0dba9906e2 in release 0.8.0
