### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by shakasom** [datapane/datapane#19]
I am getting this problem after upgrading to datapane 0.7.1

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\shaka\\Desktop\\C\\Drafts\\dp-cache\\dp-tmp-p4ivkaca\\dp-tmp-muexg9zv.arrow.gz'

**Comment by mands** [comment]
Hi @shakasom - thanks for opening the issue - we're aware of the cache problem when running datapane on Windows and will be pushing a bug-fix in the next or two that should resolve this - thanks!

**Comment by mands** [comment]
fixed in release 0.7.2 - available on pip and conda-forge :)

**Comment by shakasom** [comment]
Thanks @mands . Excellent news.
