### ISSUE TITLE
Report creation API / DX

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#2]
# Overview

A single report can be created with `Report.create([components], [options])`, such as:

```python
report = [
    Plot.create(my_plot),
    Markdown("# My Markdown"),
    Table.create(my_table)
]

# Alternatively: LocalReport.create(*report)
Report.create(*report)
```

This is different from the DX of how you create a report dynamically via running a script on Datapane (right now on Datapane.com, soon to be on the open source offering too). I believe this is due to the fact that the actual report generation happens outside of the user's code when running on the server.

Currently we support two options:

1. Assigning to a **magic report object**, which Datapane will look for and pick out:

#### Pros
- Shorter for smaller scripts and examples
- Easier to immediately understand with a lower cognitive overhead

#### Cons
- Magic and implicit
- Pollutes the namespace

```python
report = [
    Plot.create(my_plot),
    Markdown("# My Markdown"),
    Table.create(my_table)
]
```

2. Adding a **render function**, which returns a list of components (i.e. what is passed to `Report.create`)

#### Pros
- Doesn't polute global object namespace
- Doesn't run with script in regular circumstances, so more portable

#### Cons
- Harder to understand on first glance
- Currently introduces a larger divergeence between ad-hoc report generation, and script/dynamic report generation

```python
def render():
    return [
        Plot.create(my_plot),
        Markdown("# My Markdown"),
        Table.create(my_table)
    ]
```
-----

# Notes
- When developing locally, you want to be able to preview your report output regularly, without having to run the script -- a user would probably always be developering using `Report.create`, and then switch to the server version before deploying. From my POV, the ideal DX would be to be able to use the same code.
  - Alternatively, we could just add a helper to the datapane library, like `dp.preview_report()` which calls render and creates a `LocalReport`, or looks for the `report` object and does the same.
-----

# Questions
- Do we keep both or one?
- What is a solution that unifies the local dev story with deploying the script?
- Is there a third option? i.e. `dp.report = []`, or using the same `Report.create` syntax, but just making it work on the server.

**Comment by mands** [comment]
closed by datapane/datapane-hosted#45
