### ISSUE TITLE
Datapane Report templates

### ISSUE THREAD

**Issue by mands** [datapane/datapane#20]
**Is your feature request related to a problem? Please describe.**
- Users should have a sample report code available when using the CLI

**Describe the solution you'd like**
- A new command, `datapane report init` that generates a sample report, that upon running generates a simple report for local / publishing usage

**Describe alternatives you've considered**
- We could tie this into GH template repos to pull down templates from hosted repos that can be updated / improved by the wider community

**Comment by lanthias** [comment]
+1 - this is a good idea - currently the report generated on init is a bit barebones, so having some more richer examples would be good. It would be good to think about how this ties into reports potentially including source code too.
