### ISSUE TITLE
Remove upper Bokeh version pin

### ISSUE THREAD

**Issue by jonmmease** [datapane/datapane#200]
Hi, I was wondering if it would be possible to remove datapane's upper version constraint on Bokeh version 2.2.  Bokeh is now up to version 2.4.2, and it would be nice to take advantage of the new features.
Thanks!

**Comment by lanthias** [comment]
Thanks for the suggestion @jonmmease. Sounds like a good idea. We are looking into this now and will get back to you shortly!

**Comment by shahinrostami** [comment]
Hello @jonmmease, thanks again for raising this!

I can confirm the current Datapane release works with later versions of Bokeh (thank you @Buroni 👍). From my test environment

`bokeh                2.4.3        Interactive plots and applications in the browser from Python`

Please let us know if anything else comes up!
