### ISSUE TITLE
Issue Installing DataPane

### ISSUE THREAD

**Issue by Shespeaks-data** [datapane/datapane#204]
### System Information

- OS: MAC M1 
- Python version: 3.9.7
- Python environment: conda
- Using jupyter: true 
- Datapane version:

### Bug / Issue

Issue installing Datapane 
-->

<img width="688" alt="Screenshot 2022-05-30 at 12 14 41" src="https://user-images.githubusercontent.com/105555845/170981083-7697d446-78c4-40f3-a54f-a44e6b549f67.png">

**Comment by lanthias** [comment]
Thanks for the issue @Shespeaks-data. @mands I was wondering if this could be related to the fact that the conda install instructions on the website are hardcoded at 0.10.0, whereas before they were tracking the latest version on conda itself.

**Comment by shahinrostami** [comment]
Hello @Shespeaks-data!

Can you try installing Datapane 0.14.0 instead? 

- Within the command line: `conda install -c conda-forge "datapane>=0.14.0"`
- Within Jupyter Lab: `!conda install -c conda-forge "datapane>=0.14.0 -y"

Please let us know how it goes!

**Comment by Shespeaks-data** [comment]
Hi, I tried that too, no difference . Still inconsistent environment
<img width="901" alt="Screenshot 2022-05-31 at 14 21 57" src="https://user-images.githubusercontent.com/105555845/171183607-7c62ba0c-7ecc-499b-bf68-d0a38935a609.png">

**Comment by Shespeaks-data** [comment]
hello, Im super thankful for all the help. 
I attempted these steps, here's what I got 
![Uploading Screenshot 2022-05-31 at 17.57.15.png…]()
![Uploading Screenshot 2022-05-31 at 17.58.04.png…]()

**Comment by Shespeaks-data** [comment]
Hello,im super thankful for all your help
I tried these.


<img width="660" alt="Screenshot 2022-05-31 at 17 57 15" src="https://user-images.githubusercontent.com/105555845/171233189-ac952f83-fc65-4bd6-873a-fac8ff5604ea.png">
<img width="653" alt="Screenshot 2022-05-31 at 17 58 04" src="https://user-images.githubusercontent.com/105555845/171233285-a928f949-38ae-43a7-a58e-6173c2cfffc7.png">

**Comment by shahinrostami** [comment]
> I think it worked!!!
> <img alt="Screenshot 2022-06-01 at 11 09 35" width="969" src="https://user-images.githubusercontent.com/105555845/171384489-49654834-9893-4b2c-b300-4b5f28107265.png">

That's great news! I hope you enjoy working with Datapane 🎉🚀
