### ISSUE TITLE
Update to pyarrow 1.0.0

### ISSUE THREAD

**Issue by tazimmerman** [datapane/datapane#21]
**Is your feature request related to a problem? Please describe.**
The conda package is pinned to pyarrow 0.17.*, but I'd like to use pyarrow 1.0.0 functionality.

**Describe the solution you'd like**
Is it possible to remove the pin on 0.17.* and update the dependency to 1.0.0? I'm happy to help with testing if you need an extra set of hands.

**Comment by lanthias** [comment]
Thanks for the note! We definitely want to support 1.0.0 ASAP. The current blocker is that we use the javascript library in reports to deserialize datasets. Although Arrow itself is at 1.0.0, I do not believe the current typescript/js library supports this, as [it seems to still be on 0.17.0](https://www.npmjs.com/package/apache-arrow).

When they release this, we would absolutely love an extra set of hands - thanks! :)

**Comment by mands** [comment]
closing as we've updated to pyarrow 2.0.0 in `master` - this should be released in the next week or so
