### ISSUE TITLE
dp.Select not displaying correctly with 10 selects on a page

### ISSUE THREAD

**Issue by paulhighams** [datapane/datapane#215]
### System Information

- OS:
- Python version: 3.9
- Python environment: pip 
- Using jupyter: false
- Datapane version: ?

### Bug / Issue

I have a page with 10 select blocks. A drop down lists the 10 blocks correctly, all the 10 blocks are selectable. So far so good.
When you select a block from the dropdown, it displays but the block selected is not shown correctly in the drop dowm, so you don't know which block you are looking at.

https://datapane.com/reports/VkBWjZA/ifsc-world-cup-event-statistics/

go to the country results world cups tab and try the dropdown, the text in the dropdown doesn't change when you pick from the list.
This does work ok on other tabs with a dropdown with <10 entries.

**Comment by lanthias** [comment]
Thanks for the issue @paulhighams. Adding @Buroni who looks after this bit of the codebase.

**Comment by paulhighams** [comment]
thanks, thats great.

**Comment by shahinrostami** [comment]
Hey @paulhighams! 

We'll keep the issue open until the release, that way anyone searching for the same answer will be in the loop!

**Comment by gelliot-os** [comment]
@shahinrostami I am experiencing this as well.  Is there a version I should target to attempt to resolve this?

**Comment by shahinrostami** [comment]
> @shahinrostami I am experiencing this as well. Is there a version I should target to attempt to resolve this?

Hello @gelliot-os ! 

We're pushing a new release soon which resolves this issue - we've kept it open in the meantime.

**Comment by shahinrostami** [comment]
Hello @paulhighams ! Happy to say this made it into our recent release and should be resolved. I checked the awesome report here https://datapane.com/reports/VkBWjZA/ifsc-world-cup-event-statistics/ and it appears to be working. Please let us know if there's anything else!
