### ISSUE TITLE
visibility flag on report upload not working

### ISSUE THREAD

**Issue by paulhighams** [datapane/datapane#216]
### System Information

- OS:
- Python version: 3.8.5
- Python environment: pip
- Using jupyter: false
- Datapane version: ?

### Bug / Issue

visibility = dp.Visibility.DEFAULT, when this is added to the report upload it does not "tick" the publicly visible box on the report settings page. 
My understanding of the documentation is that this property would tick that box, at the moment I have to remember to tick the box every time I upload the report.

**Comment by lanthias** [comment]
Thanks for this and good catch. I've looked into this and there is a mistake in our docs, as `visibility` as been deprecated and replaced with a boolean field, `publicly_visible`, which you can use as follows:

`dp.Report(...).upload(name='foobar', publicly_visible=True)`

I've updated the docs (which are currently being rewritten to fix a lot of these discrepancies)

**Comment by paulhighams** [comment]
Just tried this now. Perfect, stops me forgetting to make reports visible :)
