### ISSUE TITLE
How to remove vertical scroll bar in embedded use

### ISSUE THREAD

**Issue by pstrato-agrimetrics** [datapane/datapane#233]
### System Information

- OS: windwos
- Python version: 3.9
- Python environment: pip 
- Using jupyter:  false
- Datapane version: 0.14.0

### Issue
When using the embedded code (e.g. <iframe src="https://datapane.com/reports/dkjbmrk/agrimetrics-croplens-ai-winter-barley-estimation/embed/" width="100%" height="540px" style="border: none;">IFrame not supported</iframe>), the report is always displayed with a vertical scroll bar. Can this scroll bar be deleted or hidden?

**Comment by shahinrostami** [comment]
Hey @pstrato-agrimetrics ! Can you please share a screenshot where the problem presents itself?

**Comment by pstrato-agrimetrics** [comment]
Hi @shahinrostami 
For example, in https://docs.datapane.com/reports/blocks/plots-and-visualizations, the vertical scroll bar is visible on the Altair example.
![image](https://user-images.githubusercontent.com/25479785/182103743-79aa27b2-3f06-41fa-9872-39999f6be1f6.png)
I'm not familiar with html & css to understand if the scroll bar can be removed.
Thanks for your help

**Comment by shahinrostami** [comment]
Hello @pstrato-agrimetrics !

Thank you for raising this. I was able to reproduce the issue with the examples you've shared – this will help us work towards a fix! I did notice that not all reports have this behaviour (padding around the report through `py-4`), e.g.

```html
<iframe src="https://datapane.com/reports/M7bNod7/reporthtml/embed/" width="100%" height="700px" style="border: none;">IFrame not supported</iframe>
```

👋 @Buroni, any clues on the issue?

**Comment by Buroni** [comment]
I can repro too, this looks like a bug. Will look into this tomorrow and update here

**Comment by shahinrostami** [comment]
Hey @pstrato-agrimetrics - it looks like this has been fixed! Check out the following example:

```html
<iframe src="https://datapane.com/reports/dkjbmrk/agrimetrics-croplens-ai-winter-barley-estimation/embed/" width="100%" height="640px" style="border: none;">IFrame not supported</iframe>
```

<img width="1102" alt="Screenshot 2022-09-06 at 17 58 06" src="https://user-images.githubusercontent.com/15690380/188695898-38c0903e-f4c8-4a2f-9731-fc92b8f58a30.png">


Please let us know if there's anything else 🚀

**Comment by pstrato-agrimetrics** [comment]
Thank you
