### ISSUE TITLE
Allow local report assets to be loaded via CDN

### ISSUE THREAD

**Issue by Buroni** [datapane/datapane#25]
**Is your feature request related to a problem? Please describe**
We bundle all of npm packages inside local reports whether they're needed or not. This leads to reports being unnecessarily bloated -- see https://github.com/datapane/datapane/issues/24 and [this thread](https://discuss.datapane.com/t/ballooning-report-sizes-with-plotly/25) for examples.

**Describe the solution you'd like**
We provide a `use_cdn` option on the `Report` constructor that allows the user to load our entire report bundle (report source code + npm assets) via our own CDN. This bundle can be code-split as our hosted instance is, to prevent unnecessary packages being sent over.

**Describe alternatives you've considered**
* Inspecting the report XML prior to local report generation, then including only the required JS chunks needed by the assets inside each specific report. However parcel expects code-split chunks to be loaded over HTTP, and I can't see anything on their docs to change that.
* Compiling the report bundle on-the-fly inside `Report.save` so that we can shake off unused packages. However this would make the `save` method unacceptably slow (>1 minute on most machines), and it means we'd have to ship parcel with the API.

**Additional context**
Adding the option to use a Datapane CDN means we'd need to track versions on our report builds. I.e. if a report bundle is built with `v0.7.6`, then it should always point to `/datapane-js/v0.7.6.js`.

**Comment by drozzy** [comment]
How was this resolved?
My html files are still 3mb+
For commiting to git it's a bit heavy compared to just saving an altair graph as an png image and linking to it from html file

**Comment by codelancers-sd** [comment]
@Buroni Will it be possible to re-open the issue? 
I do not see a `use_cdn` option while creating or saving the report.

**Comment by Buroni** [comment]
Hey @codelancers-sd @drozzy we removed this feature a while ago, and are currently looking again into several options for reducing the local report file sizes. This feature is quite high-demand so I will look into publicly tracking this feature's progress either on github or datapane.com, and get back to you here.

**Comment by shahinrostami** [comment]
Hey all! Just a follow up to confirm that we have "Make reports smaller in size" on our roadmap now! You can track it for updates here: https://datapane.nolt.io/roadmap 🎉
