### ISSUE TITLE
Can datapane be integrated into a project? For example, in Vue framework

### ISSUE THREAD

**Issue by FredericaErath** [datapane/datapane#259]

**Comment by shahinrostami** [comment]
Hey @FredericaErath!

Do you mean:
- Can the datapane package be used as part of a Vue project
or 
- Can datapane reports be embedded in a Vue project?

**Comment by shahinrostami** [comment]
Hey @FredericaErath! I'm closing this issue for now, but please join us on [our chat](https://chat.datapane.com) if you'd like to ask any questions!
