### ISSUE TITLE
Not possible to undo sorting operation in the .html report

### ISSUE THREAD

**Issue by antonio-catalano** [datapane/datapane#27]
**Describe the bug**
It is not a real bug but a strange behaviour.
When I create the .html report and I click one of the columns in order to sort data, it is not possible anymore to undo the sorting operation and go back to the original state.

Is it normal?

**Comment by mands** [comment]
Hi there,

Thanks for raising this - we're picking it up shortly and should have a fix released in the next week or so. HTH!
