### ISSUE TITLE
report.save not accepting "standalone" as a parameter

### ISSUE THREAD

**Issue by codelancers-sd** [datapane/datapane#287]
### System Information

- OS: Ubuntu
- Python version: 3.10.1
- Python environment: pip
- Using jupyter: true
- Datapane version: 0.15.1

### Bug / Issue

When passing `standalone` to `report.save`, I get the following error:
`TypeError: Report.save() got an unexpected keyword argument 'standalone'`

Code snippet:
`report.save("path_to_html.html", formatting=dp.ReportFormatting(width=dp.ReportWidth.FULL), author="me@gmail.com", standalone=True )`

**Comment by spookylukey** [comment]
It looks like https://datapane.github.io/datapane/report/core.html#datapane.client.api.report.core.Report is showing docs for `master` branch, and not `0.15.1`, our most recent release - the `standalone` parameter has only been added very recently, and isn't released yet.

@shahinrostami will know most about this I think.

**Comment by shahinrostami** [comment]
> It looks like https://datapane.github.io/datapane/report/core.html#datapane.client.api.report.core.Report is showing docs for `master` branch, and not `0.15.1`, our most recent release - the `standalone` parameter has only been added very recently, and isn't released yet.
> 
> @shahinrostami will know most about this I think.

Looping in @mands who knows more about our API reference docs!

**Comment by shahinrostami** [comment]
Hey @codelancers-sd - just to keep you in the loop, we are looking at a better way to manage our API docs moving forward. As @spookylukey said, the API reference is generated against `master` which contains changes that haven't made it into the release (yet). The `standalone` parameter will be available shortly!

**Comment by shahinrostami** [comment]
I've moved this to our roadmap software (https://datapane.nolt.io/27), so we can close this issue for now!
