### ISSUE TITLE
CI Failed.

### ISSUE THREAD

**Issue by natsukium** [datapane/datapane#29]
**Describe the bug**
CI failed in #28 .

**To Reproduce**
https://github.com/datapane/datapane/actions/runs/322515583

See Run Tests l.113 in datapane-multi-env (3.6, ubuntu-latest).

**Comment by mands** [comment]
Thanks for the pointer @natsukium - I think I see the issue, there are a few pre-commit style hooks failing and potentially a `git lfs` issue - I'll try fix them up over the weekend and we should be able to merge shortly!

**Comment by mands** [comment]
Hi @natsukium - thanks for the issue and your PR - I've fixed the issues with CI and should be working now
