### ISSUE TITLE
Holoviews

### ISSUE THREAD

**Issue by Harsh-Maheshwari** [datapane/datapane#294]
Datapane does not support Holoviews plots which are basically matplotlib plots

**Comment by shahinrostami** [comment]
Hello @Harsh-Maheshwari ! 

This sounds like a great feature to look into. We manage feature requests over at https://datapane.nolt.io - it would be great to have this on there when you have the time 🙂

Will close this issue for now as we use GitHub issues for bugs at the moment 👍
