### ISSUE TITLE
Style formatted Pandas Dataframe with ,

### ISSUE THREAD

**Issue by kumarmisra** [datapane/datapane#30]
Hi ,

I am using datapane table populated with formatted pandas dataframe. The issue is out of 6 column , one column transforms to date. Rest of the 5 columns display correctly with , formatted.

**Comment by mands** [comment]
Thanks for the update - we've got some fixes for dataframe tables coming out in the next week that should fix this

**Comment by mands** [comment]
closed in c36a4eb
