### ISSUE TITLE
Can't login with a GitHub account

### ISSUE THREAD

**Issue by pstrato-agrimetrics** [datapane/datapane#304]
Hi Datapane
I'm trying to login into my existing acount. On datapane.com I onyl see a "Sign up to Cloud" button and I'm not sure this is where I should go to login into my existing account. I created my account a while ago by signing in with GitHub rather than creating an account/password. 
When I follow "Sign up to Cloud", I'm taken to:
![image](https://user-images.githubusercontent.com/25479785/196228191-9fbc5f6a-7b54-4d23-97bb-f76a3e0702cf.png)
where I click the GitHub icon. After validating my account with GitHub, I get the following error message:
![image](https://user-images.githubusercontent.com/25479785/196228049-d755c057-0d0b-47fe-b4d4-cc7ce8976a51.png)

Thanks for your help

**Comment by pstrato-agrimetrics** [comment]
The URL on the error page is:
https://datapane.com/accounts/github/login/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=TdiuXR9Wtc4J

**Comment by antdking** [comment]
Hi @pstrato-agrimetrics, thanks for raising this

We've rolled out a fix so that Github + Google authentication work again
