### ISSUE TITLE
Embedding report in medium not working

### ISSUE THREAD

**Issue by MGCal** [datapane/datapane#332]
### System Information

- OS: Windows
- Python version: 3.7.1
- Python environment: pip
- Using jupyter: true
- Datapane version: 0.15.4

### Bug / Issue

Hello, I'm trying to embed a visualization into a medium article. I've successfully created the report: https://cloud.datapane.com/apps/yklX4vk/my-plot/

When I click on share, I'm see this:

![image](https://user-images.githubusercontent.com/23065025/201077129-a20c830f-2433-4e16-a9c1-4de32f4c3dfd.png)

If I use that link in medium, I get this:

![image](https://user-images.githubusercontent.com/23065025/201077288-cadc7d32-4ed0-4fea-ae90-c33e29ddeb02.png)

I want to share it this way:

![image](https://user-images.githubusercontent.com/23065025/201077391-8e3e419b-4bce-41ce-a126-064085c4ab4d.png)

Do you know what I'm missing?

Thanks

**Comment by shahinrostami** [comment]
Thank you for raising this @MGCal ! We'll look into this and update the issue.

**Comment by lanthias** [comment]
Sometimes Medium's API gets a little borked, and I think it caches the embed requests so if it doesn't work the first time it won't in the future. 

@MGCal would you be able to try uploading the same plot on another URL and seeing if that fixes it?

**Comment by MGCal** [comment]
Sure. I'll do it right away.

**Comment by shahinrostami** [comment]
@lanthias I logged into my old Medium account and gave it a go. Seems to be broken for me, at least on my first attempt.

https://medium.com/@shahinrostami/datapane-test-6154507959c1

<img width="759" alt="Screenshot 2022-11-10 at 17 07 02" src="https://user-images.githubusercontent.com/15690380/201160633-33c9eded-a0ac-42df-8d0c-7815d158c85a.png">

**Comment by MGCal** [comment]
I've created another report: https://cloud.datapane.com/apps/E7oKxL7/thisisatest/

But I've got the same result in medium:

![image](https://user-images.githubusercontent.com/23065025/201162485-96341615-e929-4909-b803-d95dc7a4a122.png)

Let me know if you I can be of any help.

Thanks to both

**Comment by lanthias** [comment]
Thanks, that's helpful.

I've dug into this and there is an incompatibility with our new URL schema and Medium's embed support, so this won't be possible right now. We'll work with Medium to fix it.

In the mean time, would screenshotting the image of your report and linking to the interactive version on Datapane suffice for now?

**Comment by sid-ravichandran** [comment]
> I've dug into this and there is an incompatibility with our new URL schema and Medium's embed support, so this won't be possible right now. We'll work with Medium to fix it.


Hi @lanthias has there been any progress on this? I really like datapane and one of the things that drew me to it was the advertised ability to embed interactive plots in medium..

Thanks

**Comment by mands** [comment]
Hi there,

Unfortunately we're no longer able to support embedding Datapane Reports in Medium - this is an upstream issue with Medium which they do not seem to be able to fix.

Thanks for reporting the issue, in the meantime we recommend saving your reports as `html` files and using an `iframe` to embed them elsewhere.
