### ISSUE TITLE
App.save is saving singlehtml file in local but still trying to wrongly upload to events.datapane.com server 

### ISSUE THREAD

**Issue by purnendumaity** [datapane/datapane#334]
### System Information

- OS: Windows 11
- Python version: 3.10
- Python environment: pip 
- Using jupyter:  false, doing coding in Pycharm community IDE
- Datapane version: 0.15.4

**Comment by purnendumaity** [comment]
```
`import altair as alt
import datapane as dp
from vega_datasets import data
source= data.cars()
plot1 = (
    alt.Chart(source)
    .mark_circle(size=60)
    .encode(
        x="Horsepower",
        y="Miles_per_Gallon",
        color="Origin",
        tooltip=["Name", "Origin", "Horsepower", "Miles_per_Gallon"],
    )
    .interactive()
)
app = dp.App("MyFirstapp", dp.Plot(plot1,caption ="myplot"),
             dp.DataTable(source,caption="mydata"))
mypath="D:/Python-Projects/datapanetest/mytest.html"
app.save(path=mypath,open=False,standalone=True,cdn_base=None)`
```

**Comment by purnendumaity** [comment]
Below is the error screenshot
![datapane calling upload during save](https://user-images.githubusercontent.com/3212064/201524388-4103642c-a98b-43f4-a904-9085653f81f0.jpg)

**Comment by spookylukey** [comment]
This is actually not uploading the report to datapane.com, but sending analytics events to our servers. 

For this situation (where the server is unreachable for whatever reason), we shouldn't be crashing but failing more gracefully. We already have an issue logged for this, and will hopefully be able to fix it soon.

As a workaround, however, it is possible to possible to disable these analytics, which should fix the issue for you: https://github.com/datapane/datapane#analytics

**Comment by purnendumaity** [comment]
ok cool, disabling the analytics is a quick fix.. thanks a lot for your reply, you can close the issue.
