### ISSUE TITLE
Change cell limit for Table

### ISSUE THREAD

**Issue by julian-belina** [datapane/datapane#339]
Hello,

is it possible to change the cell limit of the Table object? I understand that DataTable does not have a cell constraint but the layout of the Table object fits my needs better. I am using datapane 0.15.4.

**Comment by woobe** [comment]
Hi @julian-belina what kind of cell limit do you need? Are you looking for a cell limit like "m rows x n columns"?

**Comment by julian-belina** [comment]
Yes exactly. When I try to display a large dataframe using the table object, I get an error message saying that the cell number is limited to 100 cells. I would like to increase this number even if it takes longer to create the report.

**Comment by woobe** [comment]
Got it. Let me discuss this with the team and get back to you.

**Comment by julian-belina** [comment]
A feature to (automatically) increase the row height so that the whole content of each cell could be seen without scrolling sidewards would be need. This would increase the readability of the table when inspecting the rows sequentially.

**Comment by shahinrostami** [comment]
Hello @julian-belina! 

We'll be upping the limit on `dp.Table` in an upcoming release - so we won't have to deal with the 100 cell limit for much longer. I'll leave this issue open with the `release-pending` tag for yourself and others to track until it's released.

> A feature to (automatically) increase the row height so that the whole content of each cell could be seen without scrolling sidewards would be neat. This would increase the readability of the table when inspecting the rows sequentially.

The feature sounds interesting! Please post it over on our [feature request board](https://datapane.nolt.io) where you can track it and others can pitch in too 🚀

**Comment by woobe** [comment]
@julian-belina thanks for the feedback. As @shahinrostami said, please use our [feature request board](https://datapane.nolt.io/) and make a suggestion. How many cells are you planning to show (200, 500, 1000, a lot more?)

**Comment by julian-belina** [comment]
I am using the table to display a debug log. Potentially there could be a lot of rows. In my test cases there are currently approximately 5000 cells. Having the filter features from the DataTable would great as well but the readability is the most important feature in the moment. I have created a post on the feature board.

**Comment by woobe** [comment]
Thanks for telling us about your debug log use-case. This is a great example. We will continue to look into this.

**Comment by shahinrostami** [comment]
The cell limit has been removed @julian-belina , it's available in `0.15.5`!
