### ISSUE TITLE
Add direct support for SVG images

### ISSUE THREAD

**Issue by julian-belina** [datapane/datapane#341]
Is it possible to write a method which allows the direct integration of svg images into a report? Currently I am converting my svg graphs into png files in order to include them into my report. I am not sure how this is done properly using the DataPane HTML object.

**Comment by shahinrostami** [comment]
I've just confirmed the fix in the current release of Datapane!

<img width="750" alt="Screenshot 2023-02-24 at 09 26 11" src="https://user-images.githubusercontent.com/15690380/221142195-61b7da25-6118-48bf-a93a-34a23c56c3b5.png">

Thank you for raising this. Please let us know if there's anything else 👍
