### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by do-me** [datapane/datapane#343]
Hi folks, 

(when) is Python 3.11 support planned? 

Tried to install on Ubuntu 22.04 with conda (not resolving) and pip (`pip subprocess to install build dependencies did not run successfully`), but both failed. 

Thanks!

**Comment by woobe** [comment]
Hi @do-me, thanks for reaching out. Yes, we do plan to support Python 3.11. We are waiting for all DP's dependencies to be supported by Python 3.11 right now. I will keep you posted.

**Comment by antdking** [comment]
0.16.0 is released, which adds support for python 3.11
