### ISSUE TITLE
FutureWarning from pandas to be resolved

### ISSUE THREAD

**Issue by Samreay** [datapane/datapane#352]
Hi team,

Looks like theres a line in `df_processor.py:28` that needs to have its dtype be updated.

```bash
.../datapane/common/df_processor.py:28: FutureWarning:

pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
```

I believe the change is a simple:

```python
    # flatten/reset indexes
    if isinstance(df.index, pd.RangeIndex):
        pass  # allow RangeIndex - reset numbers?
    elif isinstance(df.index, pd.Int64Index):
        df.reset_index(inplace=True, drop=True)
```

to

```python

    from pandas.api.types import is_integer_dtype

   ...

    # flatten/reset indexes
    if isinstance(df.index, pd.RangeIndex):
        pass  # allow RangeIndex - reset numbers?
    elif is_integer_dtype(df.index.dtype):
        df.reset_index(inplace=True, drop=True)
```

As per the similar fix [here](https://github.com/geopandas/geopandas/pull/2322/files) in the geopandas library.

**Comment by shahinrostami** [comment]
Thank you for raising this @Samreay! We'll be addressing several similar warnings soon - we'll make sure this one is one of them!

**Comment by TheSecurityBug** [comment]
Just started using this library and have encountered the above warning. I've tested the patch suggested by @Samreay and it does indeed resolve the pandas warnings.

This issue was closed as "not planned" however will that change?
