### ISSUE TITLE
[Bug]: Dynamic Block does not call the on_timer function

### ISSUE THREAD

**Issue by aniteicristi** [datapane/datapane#362]
### Is there an existing issue for this?

- [X] I have searched for similar issues and discussions

### Bug Description

```markdown
1. I downloaded datapane and all the relevant dependencies
2. I copy and pasted the code from this example: https://github.com/datapane/examples/blob/main/apps/stock-dashboard/app.py
3. I ran the app
4. The screen was blank
5. Nothing happened even after data was refreshed

I fought with this issue for about an hour. It comes down to the on_timer function in the Dynamic block not being called, or at least I suppose that's the problem.
```

### System Information

```markdown
- Datapane version:0.16.2
- Python version: 3.10.10
- Operating System:Linux Manjaro
- Using Jupyter: No
- Pip or Conda: Pip
- Dependencies:
```

### Anything else?

Example tested: https://github.com/datapane/examples/blob/main/apps/stock-dashboard/app.py

**Comment by aniteicristi** [comment]
Ok, so after looking through some code, I found that the version of the library I downloaded with pip is not the up-to-date version, as it is missing the changes made 2 weeks ago in this [commit](https://github.com/datapane/datapane/commit/823dea2eae1a9a4c9ec6321e8acddedda506cbb6)

**Comment by mands** [comment]
Hi @aniteicristi,

Sorry yes the fix was pushed to `master` but hasn't been released to `pip` yet - we will put out release onto `pypi` early next week.

In the meantime, there is a dev wheel of the library automatically built using the latest version on `master` that you can try using the following,

```bash
$ pip3 install https://datapane-cdn.com/python-client/dev/datapane--py3-none-any.whl
```

Hope that helps in the meantime!

**Comment by aniteicristi** [comment]
Thank you for the fast reply and the help! I'm looking forward to use datapane in my bachelor's degree license project! 

Cheers!

**Comment by mands** [comment]
Great - let us know if you have any other issues!

Closing for now - will do a pypi release next week.
