### ISSUE TITLE
Option to hide action menu (e.g. "View Source") in Altair plots

### ISSUE THREAD

**Issue by fgenoese** [datapane/datapane#38]
**Is your feature request related to a problem? Please describe.**
Altair plots always get rendered with the action menu (e.g. "View Source")

**Describe the solution you'd like**
Include option to hide this part

**Describe alternatives you've considered**
The alternative is to not use Datapane and rather rely on Altair's embed options (see [here](https://github.com/altair-viz/altair/issues/673))

**Additional context**
n/a

**Comment by mands** [comment]
Thanks for the info, we'll push out an update in the next week that allows disabling the export option when adding an Altair plot, something like `dp.Plot(plot, actions=False)`

**Comment by fgenoese** [comment]
This is great!

You might consider the possibility to pass on the full parameter list, which in Altair is done with:
`plot.save('page.html', embed_options={"actions":{"export": True, "source": False, "compiled": False, "editor": False}})`

Syntax in Datapane could therefore be:
`dp.Plot(plot, actions={"export": True, "source": False, "compiled": False, "editor": False})`

**Comment by fgenoese** [comment]
@mands if the latter solution is too specific, your original suggestion would also be ok, i.e. `dp.Plot(plot, actions=False)`

**Comment by mands** [comment]
partially fixed in c36a4eb - altair menu no longer shows by default
