### ISSUE TITLE
Table function changing dates (-1) from Pandas DataFrame upon execution

### ISSUE THREAD

**Issue by JCP281** [datapane/datapane#40]
Hello, 

I am using DataPane to create a simple report to track historical metric values, day over day. The data is being read in via Pandas excel function to a DataFrame and then I am creating a graph in plotly to visualize it. I am trying to leverage the table function in DataPane to also give the raw data along with the graph. I noticed that the dates are shifting with respect to the data. The first date in my file is September 1st, yet it is shifting everything back 1 day so that the start date of the RAW Data table output is August 31st. 

Does anyone see anything that I can do, or is this a potential bug? I know i could probably convert the dates to a string, but it seems like i shouldn't have to do that if the table function is going to assume data types. 

![image](https://user-images.githubusercontent.com/41090030/98984892-66c2ff00-24e8-11eb-9693-84463acb760c.png)

[DataPaneTest.xlsx](https://github.com/datapane/datapane/files/5532675/DataPaneTest.xlsx)

`
import pandas as pd
import datapane as dp
import plotly.graph_objects as go
import plotly.io as pio

HistoricalData = pd.read_excel(r'mypath\DataPaneTest.xlsx')
HistoricalData['DataDate'] = HistoricalData['DataDate'].astype('datetime64[ns]')

pio.templates.default = "plotly_dark"

fig = go.Figure()
fig.add_trace(go.Scatter(x=HistoricalData['DataDate'], y=HistoricalData['col1'],
                    mode='lines+markers',
                    name='t1'))
fig.add_trace(go.Scatter(x=HistoricalData['DataDate'], y=HistoricalData['col2'],
                    mode='lines+markers',
                    name='t2'))
fig.add_trace(go.Scatter(x=HistoricalData['DataDate'], y=HistoricalData['col3'],
                    mode='lines+markers',
                    name='t3'))
fig.add_trace(go.Scatter(x=HistoricalData['DataDate'], y=HistoricalData['col4'],
                    mode='lines+markers',
                    name='t4'))
fig.update_layout(
    title_text='t0',title_x=0.5)

dp.Report(
    dp.Markdown("# Stuff"),
    dp.Markdown(" "),
    dp.Plot(fig),
    dp.Markdown(" "),
    dp.Markdown("## RAW Data"),
    dp.Table(HistoricalData)
    
    
).save(path=r'mypath\DataPaneTest.html', open=True)
`

_Originally posted by @JCP281 in https://github.com/datapane/datapane/discussions/39_

**Comment by mands** [comment]
Thanks for raising this - we're planning on digging into the date handling and the table component as a whole next week, I think it may be related to some JS timezone handing in our table report code but we'll fix it very shortly as a few users have had issues with dates.

In the meantime, I can suggest converting to a string until the fix comes out - so sorry for the inconvenience!

**Comment by JCP281** [comment]
> Thanks for raising this - we're planning on digging into the date handling and the table component as a whole next week, I think it may be related to some JS timezone handing in our table report code but we'll fix it very shortly as a few users have had issues with dates.
> 
> In the meantime, I can suggest converting to a string until the fix comes out - so sorry for the inconvenience!

Hey @mands,  

Any luck? Anything i can help with on my end to test out?

**Comment by Buroni** [comment]
Hey @JCP281 I've been fixing some issues related to our date parsing, including this one that you've raised.

We have a bug in our table component that causes the client's local UTC offset to be added to the timestamp. So for example if your data contains the date `2020-11-18 20:00` and your local timezone is UTC-2, it will display `18-Nov-20 18:00`.

I think this bug may be causing the issue you're having, as I see that the dates are actually shifting back 5 hours in your case. For example the date `9/1/2020` doesn't specify hours/minutes, so it's interpreted as falling on midnight of that date. It's then being shifted to `31-Aug-20 19:00` (i.e. UTC-5).

Good news is we've identified the issue and the fix will be out with the next release!

**Comment by JCP281** [comment]
Hey @Buroni great news!

Any idea on date for when the package will be updated?

**Comment by Buroni** [comment]
@JCP281 The fix should be in early next week. I'll keep you updated on this issue

**Comment by JCP281** [comment]
Awesome. Thanks @Buroni  and @mands.

You both rock!

**Comment by Buroni** [comment]
Hey @JCP281 the timestamp fix is in now. Note that we've also changed timestamp formatting to ISO8601 with this release.

**Comment by mands** [comment]
fixed in c36a4eb
