### ISSUE TITLE
dp.Table sorting the columns in my dataframe.

### ISSUE THREAD

**Issue by joelowj** [datapane/datapane#41]
**Describe the bug**
In the previous version when passing my dataframe into dp.Table the order of the columns remain intact. 
After upgraded to 0.8.5, sorting of the columns.

**Expected behavior**
I would expect the ordering of the columns to stay the same after it is passed into dp.Table.

**Screenshots**

This is the order of the columns in the dataframe right before I passed it into dp.Table.

![image](https://user-images.githubusercontent.com/13001361/99609488-f9b0eb80-2a4a-11eb-98a7-4f8b48ceb901.png)

This is the order of the columns after I generated the report.

![image](https://user-images.githubusercontent.com/13001361/99609598-354bb580-2a4b-11eb-9990-9629820403da.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 0.8.5

**Comment by lanthias** [comment]
Hey Joel! This is a known issue affecting the current dataset viewer, particularly its treatment of columns with integer names. 

We will have a fix out next week; in the meantime, depending on the size of your dataset, you can also use the markdown component to render an HTML table, as follows:

```python
dp.Report(df.to_markdown())
```

**Comment by joelowj** [comment]
@lanthias that's great to hear! Thanks again for the hard work! This tool is amazing.

**Comment by joelowj** [comment]
In the mean time, I will close this issue. Thanks again!

**Comment by mands** [comment]
fixed in c36a4eb
