### ISSUE TITLE
Python 3.9 install failing

### ISSUE THREAD

**Issue by rakeshchalamala** [datapane/datapane#48]
Using Python3.9 and pip, the installation failing when installing pyarrow build dependencies on windows 10 pro, please help me out

**Comment by mands** [comment]
Hi there,

Thanks for your issue - we depend on `pyarrow` but unfortunately it doesn't support Python 3.9 directly/out-of-the-box without requiring compiling at the moment. I imagine they will release a pre-complied wheel to pip shortly, at which point it should work directly.

In the meantime try using an older version of Python, we support 3.6-3.8 .

Cheers!

**Comment by mands** [comment]
python 3.9 now supported
