### ISSUE TITLE
Trying to have captions with styled dataframes

### ISSUE THREAD

**Issue by FriendlyUser** [datapane/datapane#53]
**Describe the bug**

When trying to make a caption for a styled dataframe, all that is shown is a blank caption tag.

```
<caption>Some caption here</caption>

Datapane table
```

**To Reproduce**

1. Make a styled pandas DataFrame
2. Render it with datapane
3. The caption tag should be above as raw html.

**Comment by lanthias** [comment]
Thanks for the note @FriendlyUser - we currently don't support this, as we presumed that users would add text captions, but it sounds like this isn't the best behaviour and we can add it as a follow-up (currently only file-type blocks support captions). We'll keep you updated on the progress.

Thanks again!

**Comment by mands** [comment]
Yes - this should be a quick fix that we can get out very shortly - thanks for raising

**Comment by mands** [comment]
Apologies, it appears that styled tables do support captions, just add the `caption` argument when creating a `dp.Table` block, e.g.

```python
dp.Table(df, caption="My Caption")
```

And the caption should appear under your table when viewing the report. See the Blocks page on the [Demo report](https://datapane.com/u/datapane/reports/demo-report/) for sample code and demonstration.

Please let us know if that solves your issue - HTH!
