### ISSUE TITLE
Nested dp.Select not working

### ISSUE THREAD

**Issue by enra64** [datapane/datapane#54]
**Describe the bug**
In the docs concerning Select, there is a note: 

> Select expects a list of Blocks, e.g. a Plot or Table, but also including Select or Groups themselves,
      but if a Python object is passed, e.g. a Dataframe, Datapane will attempt to convert it automatically.

However, I am not able to get nested selects working. Instead, the outer selection method (tab or dropdown doesn't matter) shows, and the inner one is missing, in its place being an empty doc symbol:

![image](https://user-images.githubusercontent.com/7622426/103480499-19bb2500-4dd5-11eb-9736-9e0e2e54c3c6.png)

**To Reproduce**
Execute the following repro script:

```python
import datapane as dp


def create_plot_selection() -> dp.Select:
    test_dict = {
        "outer1": {
            "inner11label": "inner11",
            "inner12label": "inner12"
        },
        "outer2": {
            "inner21label": "inner21",
            "inner22label": "inner22",
            "inner23label": "inner23"
        }
    }

    outer_choice_blocks = []
    for outer_choice_label, inner_choices in test_dict.items():
        inner_choice_blocks = []
        for label, test_item in inner_choices.items():
            inner_choice_blocks.append(dp.Text(test_item, label=label))

        outer_choice_blocks.append(dp.Select(blocks=inner_choice_blocks, label=outer_choice_label, type=dp.SelectType.TABS))

    return dp.Select(blocks=outer_choice_blocks, type=dp.SelectType.DROPDOWN)


report = dp.Report(blocks=["Should see more than a document icon after selecting an outer choice:", create_plot_selection()])
report.save(path='report.html')
````

**Expected behavior**
When opening the generated report, I'd expect to be able to use an inner select

**Desktop (please complete the following information):**

- OS: Linux Mint 20, 
- Browser: Firefox on Linux, 
- Version 84.0.1 (64-bit) on Linux, on android 

**Smartphone (please complete the following information):**

- Device: Redmi 7
- OS: Android 10
- Browser: Firefox and Chrome
- Version: firefox 84.1.2 and chrome 87.0.4280

**Comment by enra64** [comment]
Just found out it works if I wrap the inner select in a group, i.e. `outer_choice_blocks.append(dp.Group(blocks=[dp.Select(blocks=inner_choice_blocks, label=outer_choice_label, type=dp.SelectType.TABS)]))`

**Comment by lanthias** [comment]
Thanks a lot for your feedback @enra64 - this is really helpful, and glad you found a solution eventually. We've just looking into this and will get back to you as soon as we have an answer.

**Comment by mands** [comment]
Hi @enra64 - thanks for raising this! 

Yes, nested selects (and groups) are supported by the report data model - it seems like there is a bug here breaking it at the moment. We'll start work on a small fix to this, in the meantime, as you've noticed, you can wrap things up in a intermediary `Group`.

**Comment by mands** [comment]
@Buroni - have added a unit test on the CLI side and can successfully generate valid reports with nested Selects - I think the issue may be on the FE renderer

**Comment by Buroni** [comment]
@mands Yep the FE deserialiser doesn't allow `Select`s to be direct ancestors of other `Select`s. Should be quick to allow this though.
