### ISSUE TITLE
Date column coercion bug

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#58]
_Originally posted by @ehsen in https://github.com/datapane/datapane/discussions/50_:

I have a pandas dataframe with date column in 'd-m-Y' format, the date column is string not datetime. But when I create datapane report it automatically converts my date to ISO format. Similarly I have another column with int datatype, datapane also converts it into ISO date (which is very weird).

Can you please tell me how can I fix this.

**Comment by mands** [comment]
Hi @ehsen - thanks for raising the issue - yes we're actively working on improving our date cocercion support right now and should have a much improved process rolled out shortly.

**Comment by mands** [comment]
closed in c36a4eb
