### ISSUE TITLE
Can’t deserialize Blocks at page level

### ISSUE THREAD

**Issue by kumarmisra** [datapane/datapane#62]
My reports were working until last week. This week when I returned , it’s not working any more. When I open the html page it shows blank. On chrome I see error as attached stating 

Can’t deserialize Blocks at page level

While debugging on Edge it shows https://data pane.com/static/ReactToastify.css.map could not be loaded.
![image](https://user-images.githubusercontent.com/10179139/103591204-b00e4a00-4eac-11eb-9167-ff844392f100.jpg)

**Comment by mands** [comment]
Hi @kumarmisra ,

Thanks for raising the issue - a similar issue can be found in our discussions at https://github.com/datapane/datapane/discussions/56 .

Essentially we've pushed some updated to Datapane, and as such older reports which were not generated in standalone mode will need to be regenerated after updating the library (`pip3 install -U datapane`). You can just update datapane and re-run your reports.

As part of this update, we have added a feature which will mean that you don't need to do this in the future - the reports will always select the correct rendering code from our site.

Additionally, when saving your reports, you can also use the standalone argument, e.g. report.save("report.html", standalone=True) - this will embed all the code required to run the report in the HTML file, meaning that those reports will always keep working (however each report will be a _lot_ larger so it depends on your use-case). 

Sorry for the inconvenience - hopefully the changes we've made also mean that your reports won't break going forwards either way!
