### ISSUE TITLE
table generated using DataTable,  shows column value as time duration(0 days 00:00:00.000000068)

### ISSUE THREAD

**Issue by blnprasad** [datapane/datapane#78]
![sample](https://user-images.githubusercontent.com/9347569/107137241-8ecbce00-6930-11eb-9425-e6400415043f.png)

**Describe the bug**
For below data, column value being shows as time duration on generated html report. Its happening only to that column. If i convert to int  or some string that canot be convert to int(like adding any alpha character) its being shown expected. 

 converting below dictionary( json array) to DF and trying to generate table and it seems that one particular column being showed as time duration in report.
data = [{'a': 0, 'b': 8.222222222222221, 'c': -107.0, 'd': "68"}]
df = pd.DataFrame.from_dict(ch_table)

in the report i see 'd' column being displayed as time duration(0 days 00:00:00.000000068).

**Comment by mands** [comment]
Can you confirm your version of datapane and try upgrading it (`pip install --upgrade datapane`) as many time/date related issues were fixed in version `0.9.2`

**Comment by blnprasad** [comment]
I was using 0.9.0. with 0.9.2 I don't see this issue anymore.
Thanks
