### ISSUE TITLE
Not able to re

### ISSUE THREAD

**Issue by iGSRi** [datapane/datapane#83]
**While executing below code:**

import pandas as pd
import altair as alt
import datapane as dp

df = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/GOOG?period2=1585222905&interval=1mo&events=history')

chart = alt.Chart(df).encode(
    x='Date:T',
    y='Open'
).mark_line().interactive()

r = dp.Report(dp.DataTable(df), dp.Plot(chart))
r.save(path='report.html', open=True)

**Getting error:**
ValueError: No objects to concatenate

ValueError                                Traceback (most recent call last)
<ipython-input-28-f005ecca2f7b> in <module>
     10 ).mark_line().interactive()
     11 
---> 12 r = dp.Report(dp.DataTable(df), dp.Plot(chart))

**Comment by mands** [comment]
Can you provide the full error/stacktrace?

**Comment by mands** [comment]
I've just ran your code locally on my machine (using Datapane 0.9.2 on Python 3.8 under Linux) and can not reproduce the issue - perhaps there was an error in downloading the csv file.

**Comment by mands** [comment]
closing as can't reproduce - please feel free to open if you have more info/issues
