### ISSUE TITLE
ruamel-yaml (distutils) install issue

### ISSUE THREAD

**Issue by lanthias** [datapane/datapane#84]
_Originally posted by @ahull002 in https://github.com/datapane/datapane/discussions/80_

**System:** O365/WIN10

**IDE:** JupyterLab 3.0.7

**Language:** Python version 3.8.5

**Library:** datapane

**Issue:** 
Hello, I keep getting package errors when trying to install the datapane. The errors surround ruamel-yaml (distutils) and DLL.

**Steps taken:**

I have tried installing this two ways via PiP and Conda:

**1. Via PiP:** 

`"ERROR: Cannot uninstall 'ruamel-yaml.' It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."`

**2. Via Conda:**
`ImportError: DLL load failed while importing lib: The specified procedure could not be found.`

Any assistance or light to help me navigate what these issues are and how to get around them would be awesome. Thank you.

**Comment by mands** [comment]
I'd say in most cases this would be solved by creating a new pip venv or conda environment and installing datapane there - as in this case it seems there is an older system version of `ruamel` installed. We can look at increase our library bounds to help here also

**Comment by ahull002** [comment]
@mands will the team take action on this, or is there something additional you would like me to try to see if I can get it to work. I noticed you mentioning increasing the library bounds to help. Will you notify this thread once that is done so that I can try it out?

**Comment by mands** [comment]
Hi @ahull002 - yes we plan to try to increase the library bounds and remove some dependencies in the next week or so, in the meantime if you are still hitting issues please try in a new pip venv or conda environment.

We'll make sure to ping the thread when the update goes out - cheers!

**Comment by mands** [comment]
please try the recent 0.10.4 release - `ruamel-yaml` and many other libraries that can cause issues have been removed / made optional - HTH!
