### ISSUE TITLE
client is out-of-date but unable to update

### ISSUE THREAD

**Issue by XD-Ooi** [datapane/datapane#89]
### System Information
- OS:  Windows 10
- Python version: 3.8.5
- Python environment: conda
- Using jupyter: true 
- Datapane version: 0.9.2

### Bug / Issue
I received the error: `Your client is out-of-date (version 0.9.2) and may be causing errors, please upgrade to version 0.10.1
Please visit www.github.com/datapane/datapane to raise issue / discuss if error repeats` after keying in my API token to login. 

However, when I tried `conda install -c conda-forge "datapane>=0.10.1"`, there are too many conflicts with existing packages listed and I am unsure what my next steps of action should be. I've attached the conflicts in the following txt file for your reference.
[datapane update conflicts.txt](https://github.com/datapane/datapane/files/6087312/datapane.update.conflicts.txt)

Much thanks!

**Comment by mands** [comment]
Hi there, sorry about this - please try running `conda update --all` or try in a new conda environment, e.g. `conda create -n {NAME}` and `conda activate {NAME}`

**Comment by mands** [comment]
Hi, please try using the recently released 0.10.4 version which includes fewer libraries and so should install in more environments. Thanks!

**Comment by XD-Ooi** [comment]
Sure thing, thanks!
