### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by cornzyblack** [datapane/datapane#9]
Hi am currently encountering an error when I try to run one of the codes in the tutorial.

```python
import pandas as pd
import datapane as dp
import numpy as np


df = pd.DataFrame(
    {"A": np.random.normal(-1, 1, 5000), "B": np.random.normal(1, 2, 5000),}
)

table = dp.Table(df)
report = dp.Report(table)
report.save(path="test.html")
```

I get this error 

> UnicodeEncodeError: 'charmap' codec can't encode character '\ue6c6' in position 232206: character maps to <undefined>

#### Python versions tried
- Python 3.8.3 
- Python 3.6.8 

#### Modules installed:
- datapane 0.6.2
- pandas 1.0.3
- numpy 1.18.2

**Comment by lanthias** [comment]
hey @cornzyblack thanks for the issue! I believe this is because default encoding on windows isn't utf-8 (as it is on linux & mac) - wdyt @mands? We will try and get to it as soon as we can.

**Comment by mands** [comment]
fixed upstream and releasing asap as version `0.6.3` on `pip`
